name: LibelulaClimber
version: "1.1.2 Alpha"
main: me.libelula.climber.Main
description: Libelula Climber Minigame
author: Diego Lucio D'Onofrio <ddonofrio@member.fsf.org>
website: http://libelula.me
depend: [TagAPI, WorldGuard, WorldEdit]
commands:
    lclsetup:
        description: Configures new arenas.
        permission: lcl.admin
        usage: /lclsetup
        permission-message: You don't have <permission>
    lcl:
        description: Players command
        permission: lcl.player
        usage: /lcl join [team]
        permission-message: You don't have <permission>        