name: Libelula Evento Hiipo 50k
version: "0.0.6 Beta"
main: me.libelula.eventohiipo50k.Main
description: Libelula Evento Hiipo 50k
author: Diego Lucio D'Onofrio <ddonofrio@member.fsf.org>
website: http://libelula.me
